# https://travis-ci.org/#!/phlax/protobuf2dev

dist: bionic

install:
  - make image

script:
  - docker images

before_deploy:
  - echo $DOCKER_ACCESS_TOKEN | docker login -u phlax --password-stdin

deploy:
  provider: script
  script: make hub-image
  skip_cleanup: true
  on:
    all_branches: true
    condition: $TRAVIS_BRANCH =~ ^(master)$
